SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS file;
DROP TABLE IF EXISTS image;
DROP TABLE IF EXISTS exif;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS access;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE album (
	id MEDIUMINT NOT NULL AUTO_INCREMENT, 
	name VARCHAR(255) NOT NULL COMMENT 'The name of the album',
	path VARCHAR(4096) NOT NULL COMMENT 'path to the album',
	caption TEXT DEFAULT NULL COMMENT 'The caption of the album',
	parent MEDIUMINT DEFAULT NULL COMMENT 'Parent album, null if top level album',
	public BOOLEAN DEFAULT TRUE COMMENT 'if the album public',
	FOREIGN KEY (parent) REFERENCES album(id) ON DELETE CASCADE,
	INDEX path_index (path),
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE image (
	id MEDIUMINT NOT NULL AUTO_INCREMENT, 
	path VARCHAR(4096) NOT NULL COMMENT 'The path to the file in question',
	album MEDIUMINT DEFAULT NULL COMMENT 'In what album it is',
	name VARCHAR(255) NOT NULL COMMENT 'The name of the file',
	caption TEXT DEFAULT NULL COMMENT 'Caption of the image',
	width SMALLINT UNSIGNED DEFAULT NULL COMMENT 'width of image',
	height SMALLINT UNSIGNED DEFAULT NULL COMMENT 'height of image',
	FOREIGN KEY (album) REFERENCES album(id) ON DELETE CASCADE,
	PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE exif (
	image MEDIUMINT NOT NULL,
	name VARCHAR(255) NOT NULL,
	value TEXT DEFAULT NULL,
	FOREIGN KEY (image) REFERENCES image(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE sessions (
	session_id varchar(40) DEFAULT '0' NOT NULL,
	ip_address varchar(16) DEFAULT '0' NOT NULL,
	user_agent varchar(50) NOT NULL,
	last_activity int(10) unsigned DEFAULT 0 NOT NULL,
	user_data text NOT NULL,
	PRIMARY KEY (session_id)
) DEFAULT CHARSET=utf8;

CREATE TABLE users (
	id MEDIUMINT NOT NULL AUTO_INCREMENT,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(32) NOT NULL COMMENT 'MD5 sum',
	PRIMARY KEY (id),
	UNIQUE KEY username (username)
) DEFAULT CHARSET=utf8;

CREATE TABLE access (
	user MEDIUMINT NOT NULL,
	album MEDIUMINT NOT NULL,
	FOREIGN KEY (user) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (album) REFERENCES album(id) ON DELETE CASCADE,
	PRIMARY KEY (user , album )
) DEFAULT CHARSET=utf8;
